Feature: Centrilli app login functionality
  User Story :As a registered I should be able to login to my account so that I can use the modules.

  Scenario Template: User should be able to login with valid posmanager credentials
    When User goes to centrilli login page
    And User enters username "<username>"
    And User enters password "<password>"
    And User clicks the login button
    Then User should see the home page of app

    Examples:
      | username               | password   |
      | posmanager6@info.com   | posmanager |
      | posmanager7@info.com   | posmanager |
      | posmanager8@info.com   | posmanager |
      | posmanager9@info.com   | posmanager |
      | posmanager10@info.com  | posmanager |
      | posmanager11@info.com  | posmanager |
      | posmanager12@info.com  | posmanager |
      | posmanager13@info.com  | posmanager |
      | posmanager14@info.com  | posmanager |
      | posmanager15@info.com  | posmanager |
      | posmanager16@info.com  | posmanager |
      | posmanager17@info.com  | posmanager |
      | posmanager18@info.com  | posmanager |
      | posmanager19@info.com  | posmanager |
      | posmanager20@info.com  | posmanager |
      | posmanager21@info.com  | posmanager |
      | posmanager22@info.com  | posmanager |
      | posmanager23@info.com  | posmanager |
      | posmanager24@info.com  | posmanager |
      | posmanager26@info.com  | posmanager |
      | posmanager27@info.com  | posmanager |
      | posmanager28@info.com  | posmanager |
      | posmanager29@info.com  | posmanager |
      | posmanager30@info.com  | posmanager |
      | posmanager31@info.com  | posmanager |
      | posmanager32@info.com  | posmanager |
      | posmanager33@info.com  | posmanager |
      | posmanager34@info.com  | posmanager |
      | posmanager35@info.com  | posmanager |
      | posmanager36@info.com  | posmanager |
      | posmanager37@info.com  | posmanager |
      | posmanager38@info.com  | posmanager |
      | posmanager39@info.com  | posmanager |
      | posmanager40@info.com  | posmanager |
      | posmanager41@info.com  | posmanager |
      | posmanager42@info.com  | posmanager |
      | posmanager43@info.com  | posmanager |
      | posmanager44@info.com  | posmanager |
      | posmanager45@info.com  | posmanager |
      | posmanager46@info.com  | posmanager |
      | posmanager47info.com   | posmanager |
      | posmanager48@info.com  | posmanager |
      | posmanager49@info.com  | posmanager |
      | posmanager50@info.com  | posmanager |
      | posmanager51@info.com  | posmanager |
      | posmanager52@info.com  | posmanager |
      | posmanager53@info.com  | posmanager |
      | posmanager54@info.com  | posmanager |
      | posmanager55@info.com  | posmanager |
      | posmanager56@info.com  | posmanager |
      | posmanager57@info.com  | posmanager |
      | posmanager58@info.com  | posmanager |
      | posmanager59@info.com  | posmanager |
      | posmanager60@info.com  | posmanager |
      | posmanager61@info.com  | posmanager |
      | posmanager62@info.com  | posmanager |
      | posmanager63@info.com  | posmanager |
      | posmanager64@info.com  | posmanager |
      | posmanager65@info.com  | posmanager |
      | posmanager66@info.com  | posmanager |
      | posmanager67@info.com  | posmanager |
      | posmanager68@info.com  | posmanager |
      | posmanager69@info.com  | posmanager |
      | posmanager70@info.com  | posmanager |
      | posmanager71@info.com  | posmanager |
      | posmanager72@info.com  | posmanager |
      | posmanager73@info.com  | posmanager |
      | posmanager74@info.com  | posmanager |
      | posmanager75@info.com  | posmanager |
      | posmanager76@info.com  | posmanager |
      | posmanager77@info.com  | posmanager |
      | posmanager78@info.com  | posmanager |
      | posmanager79@info.com  | posmanager |
      | posmanager80@info.com  | posmanager |
      | posmanager81@info.com  | posmanager |
      | posmanager82@info.com  | posmanager |
      | posmanager83@info.com  | posmanager |
      | posmanager84@info.com  | posmanager |
      | posmanager85@info.com  | posmanager |
      | posmanager86@info.com  | posmanager |
      | posmanager87@info.com  | posmanager |
      | posmanager88@info.com  | posmanager |
      | posmanager89@info.com  | posmanager |
      | posmanager90@info.com  | posmanager |
      | posmanager91@info.com  | posmanager |
      | posmanager92@info.com  | posmanager |
      | posmanager93@info.com  | posmanager |
      | posmanager94@info.com  | posmanager |
      | posmanager95@info.com  | posmanager |
      | posmanager96@info.com  | posmanager |
      | posmanager97@info.com  | posmanager |
      | posmanager98@info.com  | posmanager |
      | posmanager99@info.com  | posmanager |
      | posmanager100@info.com | posmanager |
      | posmanager101info.com  | posmanager |
      | posmanager102@info.com | posmanager |
      | posmanager103@info.com | posmanager |
      | posmanager104@info.com | posmanager |

  Scenario Outline: Verify that I can login with valid credentials as salesmanager
    When User goes to centrilli login page
    And User enters username "<username>" and "<password>" and pushes the enter button
    Then User should see the home page of app

    Examples:
      | username               | password   |
      | posmanager6@info.com   | posmanager |
      | posmanager7@info.com   | posmanager |
      | posmanager8@info.com   | posmanager |
      | posmanager9@info.com   | posmanager |
      | posmanager10@info.com  | posmanager |
      | posmanager11@info.com  | posmanager |
      | posmanager12@info.com  | posmanager |
      | posmanager13@info.com  | posmanager |
      | posmanager14@info.com  | posmanager |
      | posmanager15@info.com  | posmanager |
      | posmanager16@info.com  | posmanager |
      | posmanager17@info.com  | posmanager |
      | posmanager18@info.com  | posmanager |
      | posmanager19@info.com  | posmanager |
      | posmanager20@info.com  | posmanager |
      | posmanager21@info.com  | posmanager |
      | posmanager22@info.com  | posmanager |
      | posmanager23@info.com  | posmanager |
      | posmanager24@info.com  | posmanager |
      | posmanager26@info.com  | posmanager |
      | posmanager27@info.com  | posmanager |
      | posmanager28@info.com  | posmanager |
      | posmanager29@info.com  | posmanager |
      | posmanager30@info.com  | posmanager |
      | posmanager31@info.com  | posmanager |
      | posmanager32@info.com  | posmanager |
      | posmanager33@info.com  | posmanager |
      | posmanager34@info.com  | posmanager |
      | posmanager35@info.com  | posmanager |
      | posmanager36@info.com  | posmanager |
      | posmanager37@info.com  | posmanager |
      | posmanager38@info.com  | posmanager |
      | posmanager39@info.com  | posmanager |
      | posmanager40@info.com  | posmanager |
      | posmanager41@info.com  | posmanager |
      | posmanager42@info.com  | posmanager |
      | posmanager43@info.com  | posmanager |
      | posmanager44@info.com  | posmanager |
      | posmanager45@info.com  | posmanager |
      | posmanager46@info.com  | posmanager |
      | posmanager47info.com   | posmanager |
      | posmanager48@info.com  | posmanager |
      | posmanager49@info.com  | posmanager |
      | posmanager50@info.com  | posmanager |
      | posmanager51@info.com  | posmanager |
      | posmanager52@info.com  | posmanager |
      | posmanager53@info.com  | posmanager |
      | posmanager54@info.com  | posmanager |
      | posmanager55@info.com  | posmanager |
      | posmanager56@info.com  | posmanager |
      | posmanager57@info.com  | posmanager |
      | posmanager58@info.com  | posmanager |
      | posmanager59@info.com  | posmanager |
      | posmanager60@info.com  | posmanager |
      | posmanager61@info.com  | posmanager |
      | posmanager62@info.com  | posmanager |
      | posmanager63@info.com  | posmanager |
      | posmanager64@info.com  | posmanager |
      | posmanager65@info.com  | posmanager |
      | posmanager66@info.com  | posmanager |
      | posmanager67@info.com  | posmanager |
      | posmanager68@info.com  | posmanager |
      | posmanager69@info.com  | posmanager |
      | posmanager70@info.com  | posmanager |
      | posmanager71@info.com  | posmanager |
      | posmanager72@info.com  | posmanager |
      | posmanager73@info.com  | posmanager |
      | posmanager74@info.com  | posmanager |
      | posmanager75@info.com  | posmanager |
      | posmanager76@info.com  | posmanager |
      | posmanager77@info.com  | posmanager |
      | posmanager78@info.com  | posmanager |
      | posmanager79@info.com  | posmanager |
      | posmanager80@info.com  | posmanager |
      | posmanager81@info.com  | posmanager |
      | posmanager82@info.com  | posmanager |
      | posmanager83@info.com  | posmanager |
      | posmanager84@info.com  | posmanager |
      | posmanager85@info.com  | posmanager |
      | posmanager86@info.com  | posmanager |
      | posmanager87@info.com  | posmanager |
      | posmanager88@info.com  | posmanager |
      | posmanager89@info.com  | posmanager |
      | posmanager90@info.com  | posmanager |
      | posmanager91@info.com  | posmanager |
      | posmanager92@info.com  | posmanager |
      | posmanager93@info.com  | posmanager |
      | posmanager94@info.com  | posmanager |
      | posmanager95@info.com  | posmanager |
      | posmanager96@info.com  | posmanager |
      | posmanager97@info.com  | posmanager |
      | posmanager98@info.com  | posmanager |
      | posmanager99@info.com  | posmanager |
      | posmanager100@info.com | posmanager |
      | posmanager101info.com  | posmanager |
      | posmanager102@info.com | posmanager |
      | posmanager103@info.com | posmanager |
      | posmanager104@info.com | posmanager |